/** @type {import('tailwindcss').Config} */
export default {
  content: [
    './index.html',
    './src/**/*.{js,ts,jsx,tsx}',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'on-primary-fixed': '#1c1b1b',
        'on-primary-fixed-variant': '#474646',
        'surface-container': '#f0ede9',
        'on-error-container': '#93000a',
        'surface-container-high': '#eae8e4',
        surface: '#fcf9f5',
        'surface-variant': '#e5e2de',
        background: '#fcf9f5',
        'inverse-primary': '#c8c6c5',
        'tertiary-fixed-dim': '#c6c7c2',
        'on-tertiary-container': '#838480',
        'surface-tint': '#5f5e5e',
        'on-background': '#1c1c1a',
        'on-secondary-fixed': '#241a00',
        'error-container': '#ffdad6',
        'on-surface': '#1c1c1a',
        'inverse-surface': '#31302e',
        'on-secondary-fixed-variant': '#574500',
        'surface-dim': '#dcdad6',
        'on-secondary-container': '#745c00',
        outline: '#747878',
        'secondary-fixed': '#ffe088',
        'primary-fixed': '#e5e2e1',
        'on-tertiary-fixed': '#1a1c19',
        'on-secondary': '#ffffff',
        'tertiary-fixed': '#e3e3de',
        'surface-container-lowest': '#ffffff',
        'tertiary-container': '#1a1c19',
        'secondary-container': '#fed65b',
        'primary-container': '#1c1b1b',
        'outline-variant': '#c4c7c7',
        error: '#ba1a1a',
        'primary-fixed-dim': '#c8c6c5',
        'on-primary-container': '#858383',
        'on-surface-variant': '#444748',
        'on-error': '#ffffff',
        primary: '#000000',
        'secondary-fixed-dim': '#e9c349',
        secondary: '#735c00',
        'on-primary': '#ffffff',
        'surface-bright': '#fcf9f5',
        'surface-container-highest': '#e5e2de',
        'on-tertiary-fixed-variant': '#454744',
        'on-tertiary': '#ffffff',
        'surface-container-low': '#f6f3ef',
        tertiary: '#000000',
        'inverse-on-surface': '#f3f0ec',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        gutter: '24px',
        unit: '8px',
        'margin-mobile': '20px',
        'margin-desktop': '64px',
      },
      maxWidth: {
        'container-max': '1440px',
      },
      spacing: {
        'section-gap': '120px',
      },
      fontFamily: {
        'display-lg': ['Playfair Display'],
        'headline-lg-mobile': ['Playfair Display'],
        'body-md': ['Montserrat'],
        'body-lg': ['Montserrat'],
        'headline-md': ['Playfair Display'],
        'headline-lg': ['Playfair Display'],
        'label-sm': ['Montserrat'],
      },
      fontSize: {
        'display-lg': ['64px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '400' }],
        'headline-lg-mobile': ['32px', { lineHeight: '1.2', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-lg': ['18px', { lineHeight: '1.6', letterSpacing: '0.01em', fontWeight: '300' }],
        'headline-md': ['28px', { lineHeight: '1.3', fontWeight: '400' }],
        'headline-lg': ['40px', { lineHeight: '1.2', fontWeight: '400' }],
        'label-sm': ['12px', { lineHeight: '1', letterSpacing: '0.1em', fontWeight: '600' }],
      },
    },
  },
  plugins: [],
};
